### ISSUE TITLE
npx react-native run-ios 报错

### ISSUE THREAD

**Issue by Mynini** [wutiange/log-listener-plugin#2]
error Unable to resolve module ./Server from /Users/ly/project/react_native_template/node_modules/@wutiange/log-listener-plugin/dist/src/logPlugin.js: 

None of these files exist:
  * node_modules/@wutiange/log-listener-plugin/dist/src/Server(.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * node_modules/@wutiange/log-listener-plugin/dist/src/Server
  14 | Object.defineProperty(exports, "__esModule", { value: true });
  15 | exports.SafeLogPlugin = void 0;
> 16 | const Server_1 = __importDefault(require("./Server"));
     |                                           ^
  17 | const utils_1 = require("./utils");
  18 | const HTTPInterceptor_1 = require("./HTTPInterceptor");
  19 | const common_1 = require("./common");.
Error: Unable to resolve module ./Server from /Users/ly/project/react_native_template/node_modules/@wutiange/log-listener-plugin/dist/src/logPlugin.js: 

None of these files exist:
  * node_modules/@wutiange/log-listener-plugin/dist/src/Server(.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * node_modules/@wutiange/log-listener-plugin/dist/src/Server
  14 | Object.defineProperty(exports, "__esModule", { value: true });
  15 | exports.SafeLogPlugin = void 0;
> 16 | const Server_1 = __importDefault(require("./Server"));
     |                                           ^
  17 | const utils_1 = require("./utils");
  18 | const HTTPInterceptor_1 = require("./HTTPInterceptor");
  19 | const common_1 = require("./common");
    at ModuleResolver.resolveDependency (/Users/ly/project/react_native_template/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:112:15)
    at DependencyGraph.resolveDependency (/Users/ly/project/react_native_template/node_modules/metro/src/node-haste/DependencyGraph.js:232:43)
    at /Users/ly/project/react_native_template/node_modules/metro/src/lib/transformHelpers.js:156:21
    at resolveDependencies (/Users/ly/project/react_native_template/node_modules/metro/src/DeltaBundler/buildSubgraph.js:42:25)
    at visit (/Users/ly/project/react_native_template/node_modules/metro/src/DeltaBundler/buildSubgraph.js:83:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async visit (/Users/ly/project/react_native_template/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
    at async Promise.all (index 10)
    at async visit (/Users/ly/project/react_native_template/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
info Run CLI with --verbose flag for more details.
Command PhaseScriptExecution failed with a nonzero exit code

插件包打的有问题

**Comment by wutiange** [comment]
你看看你安装的版本号是多少呀？这个是大小写的问题，之前我是小写最后我改成大写。明天我仔细看看使用新项目看看是否复现你遇到的问题

**Comment by ziwen-wang** [comment]
一样遇到 插件里引用的是大写 文件里是小写

**Comment by wutiange** [comment]
已在[2.0.2-alpha.1](https://www.npmjs.com/package/@wutiange/log-listener-plugin/v/2.0.2-alpha.1)版本中解决
